student_count = 11

puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lector"
puts "Darth Vador"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts "overall, we have #{student_count} students"
